from tkinter import *
def click(event):
    text = event.widget.cget("text")
    print(text)

    if text == "=":
        if calvalue.get().isdigit():
            value = int(calvalue.get())
        else:
            value = eval(screen.get())
        calvalue.set(value)
        screen.update()
    elif text == "C":
        calvalue.set("")
        screen.update()
    else:
        calvalue.set(calvalue.get() + text)
        screen.update()
root = Tk()
root.geometry("444x300")
root.title("Calculator")
root.config(bg="cal.jpg")

root.wm_iconbitmap("wheel.ico")
calvalue= StringVar()
calvalue.set("")
screen = Entry(root, textvariable=calvalue, font="lucida 40 bold")
screen.pack(fill=X, ipadx=4, pady=5, padx=5)

f1= Frame(root, bg="grey")
b= Button(f1, text="9", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="8", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="7", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="6", padx=6, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)

f1.pack()

f1= Frame(root, bg="grey")
b= Button(f1, text="5", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="4", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="3", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="2", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
f1.pack()

f1= Frame(root, bg="grey")
b= Button(f1, text="1", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="0", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="=", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="+", padx=5, pady=5, font="lucida 35 bold")
b.pack(side=LEFT, padx=18, pady=5)
b.bind("<Button-1>", click)
f1.pack()


f1= Frame(root, bg="grey")
b= Button(f1, text="/", padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=16, pady=10)
b.bind("<Button-1>", click)
b= Button(f1, text="%", padx=6, pady=6, font="lucida 35 bold")
b.pack(side=LEFT, padx=16, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="-", padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=16, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text="*", padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=16, pady=5)
b.bind("<Button-1>", click)
f1.pack()

f1= Frame(root, bg="grey")
b= Button(f1, text="C", padx=5, pady=8, font="lucida 35 bold")
b.pack(side=LEFT, padx=19, pady=10)
b.bind("<Button-1>", click)
b= Button(f1, text="(", padx=6, pady=6, font="lucida 35 bold")
b.pack(side=LEFT, padx=19, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text=")", padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=19, pady=5)
b.bind("<Button-1>", click)
b= Button(f1, text=".", padx=10, pady=10, font="lucida 35 bold")
b.pack(side=LEFT, padx=19, pady=5)
b.bind("<Button-1>", click)
f1.pack()
root.mainloop()